name: NodeJs feature branch workflow

# Controls when the workflow will run (Triggers on every code push)
on:
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string
      component:
        description: 'Component name'
        required: true
        type: string

env: 
  project: ${{ iputs.project }}
  component: ${{ inputs.component }}
  acc-id: 315281578625

jobs:
  trigger:   #job name
    runs-on: ubuntu-latest #github hosted runners
    steps:
        - name: clone code
          uses: actions/checkout@v7

        - name: list the files
          run: ls -la

        - name: Get version from package.json
          id: package-version
          run: |
            APP_VERSION=$(node -p "require('./package.json').version")
            echo "version=$APP_VERSION" >> $GITHUB_ENV
            echo "App version is: $APP_VERSION"

        - name: check app version
          run: echo "App version is $version"

        - name: Install dependencies
          run: npm install

        - name: Unit tests
          id: unit_tests
          run: npm test

        # - name: SonarQube Scan
        #   uses: sonarsource/sonarqube-scan-action@v3
        #   id: sonar_scan
        #   env:
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #     SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

        # - name: SonarQube Quality Gate check
        #   id: sonar-check
        #   uses: sonarsource/sonarqube-quality-gate-action@master
        #   with:
        #     pollingTimeoutSec: 600
        #   env:
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #     SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} #OPTIONAL

        - name: Check Dependabot Alerts
          id: library-scan
          uses: Posture-Cybersecurity/dependabot-security-checker@v1.1.5
          with:
            github-token: ${{ secrets.DEPENDABOT_TOKEN }}
            severities: 'critical, high' # Only check critical and high
            output-file: 'security-report.csv'
            fail-on-alerts: 'true' # Fail workflow if alerts found

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: build image
          id: build_image
          run: |
            docker build -t ${acc_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${component}:${APP_VERSION} .
          #  docker push ${acc_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${component}:${APP_VERSION}